# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/08_Model_VAE.ipynb.

# %% auto 0
__all__ = ['VAE']

# %% ../../nbs/08_Model_VAE.ipynb 3
import torch 
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

class VAE(nn.Module):
    def __init__(self, encoder, decoder):
        """
        A Varational Autoencoder (VAE) model.
        """
        super(VAE, self).__init__()
        self.encoder = encoder 
        self.decoder = decoder
    
        
    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5*logvar)
        eps = torch.randn_like(std)
        z = (mu + eps*std)
        return z

    def forward(self, x):
        mu, logvar = self.encoder(x)
        z = self.reparameterize(mu, logvar)
        x_hat = self.decoder(z)
        return x_hat,  mu, logvar
    
