# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_Losses.ipynb.

# %% auto 0
__all__ = ['CategoricalCrossEntropyLoss']

# %% ../nbs/10_Losses.ipynb 3
import torch
import torch.nn as nn
import torch.nn.functional as F

class CategoricalCrossEntropyLoss(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, y_hat, y):
        return F.nll_loss(y_hat.log(), y.argmax(dim=1))
